from django import forms
from django.db.models import Q

from account.models import User
from .models import (
    Department, Designation, Employee, EmploymentType, Holiday, LeaveRequest,
    LeaveType, Shift,
)


class StyledModelForm(forms.ModelForm):
    """Apply the project input styling consistently to all management forms."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            if isinstance(field.widget, forms.CheckboxInput):
                field.widget.attrs["class"] = "form-check-input"
            elif isinstance(field.widget, forms.Select):
                field.widget.attrs["class"] = "form-select"
            else:
                field.widget.attrs["class"] = "form-control"
            if isinstance(field.widget, (forms.DateInput, forms.TimeInput)):
                field.widget.input_type = "date" if isinstance(field.widget, forms.DateInput) else "time"


class DepartmentForm(StyledModelForm):
    class Meta:
        model = Department
        # Department code is generated by Department.save().
        fields = ("department_name", "description", "status")


class DesignationForm(StyledModelForm):
    class Meta:
        model = Designation
        # Designation code is generated by Designation.save().
        fields = ("department", "designation_name", "description", "status")


class EmploymentTypeForm(StyledModelForm):
    class Meta:
        model = EmploymentType
        fields = ("employment_type", "description", "is_active")


class LeaveTypeForm(StyledModelForm):
    class Meta:
        model = LeaveType
        fields = ("leave_name", "allowed_days", "is_paid", "is_active")


class HolidayForm(StyledModelForm):
    class Meta:
        model = Holiday
        fields = ("holiday_name", "holiday_date", "description")
        widgets = {"holiday_date": forms.DateInput(attrs={"type": "date"})}


class ShiftForm(StyledModelForm):
    class Meta:
        model = Shift
        fields = ("shift_name", "start_time", "end_time", "grace_time")
        widgets = {"start_time": forms.TimeInput(attrs={"type": "time"}), "end_time": forms.TimeInput(attrs={"type": "time"})}


class EmployeeForm(StyledModelForm):
    class Meta:
        model = Employee
        exclude = ("employee_code", "created_by", "updated_by", "created_at", "updated_at")
        widgets = {
            "date_of_birth": forms.DateInput(attrs={"type": "date"}),
            "joining_date": forms.DateInput(attrs={"type": "date"}),
            "confirmation_date": forms.DateInput(attrs={"type": "date"}),
            "relieving_date": forms.DateInput(attrs={"type": "date"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # An employee record may only be attached to an Employee-role user.
        employee_users = User.objects.filter(role__iexact="EMPLOYEE").order_by("first_name", "last_name", "username")
        print("Employee users:", employee_users)  # Debugging line to check the queryset
        if self.instance.pk and self.instance.user_id:
            employee_users = User.objects.filter(Q(pk=self.instance.user_id) | Q(role__iexact="EMPLOYEE")).order_by(
                "first_name", "last_name", "username"
            )
        self.fields["user"].queryset = employee_users
        self.fields["user"].label = "Employee user"
        self.fields["user"].help_text = "Only users assigned the Employee role are available."

        # A manager must already have an employee profile and the Manager role.
        managers = User.objects.filter(role__iexact="MANAGER").order_by("first_name", "last_name", "username")
        print("Managers:", managers)  # Debugging line to check the queryset
        if self.instance.pk and self.instance.user_id:
            employee_users = User.objects.filter(Q(pk=self.instance.user_id) | Q(role__iexact="MANAGER")).order_by(
                "first_name", "last_name", "username"
            )
        self.fields["manager"].queryset = managers
        self.fields["manager"].label = "Reporting manager"
        self.fields["manager"].help_text = "Only Users assigned the Manager role are available."

    def clean_user(self):
        user = self.cleaned_data["user"]
        if (user.role or "").upper() != "EMPLOYEE":
            raise forms.ValidationError("Select a user with the Employee role.")
        return user

    def clean_manager(self):
        manager = self.cleaned_data.get("Manager")
        if manager and (manager.user.role or "").upper() != "Manager":
            raise forms.ValidationError("Select an employee with the Manager role.")
        return manager


class LeaveRequestForm(forms.ModelForm):
    class Meta:
        model = LeaveRequest
        fields = ("leave_type", "start_date", "end_date", "reason")
        widgets = {
            "leave_type": forms.Select(attrs={"class": "form-select"}),
            "start_date": forms.DateInput(attrs={"class": "form-control", "type": "date"}),
            "end_date": forms.DateInput(attrs={"class": "form-control", "type": "date"}),
            "reason": forms.Textarea(attrs={"class": "form-control", "rows": 4, "placeholder": "Briefly explain your leave request"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["leave_type"].queryset = LeaveType.objects.filter(is_active=True).order_by("leave_name")


class LeaveReviewForm(forms.Form):
    action = forms.ChoiceField(choices=(("APPROVED", "Approve"), ("REJECTED", "Reject")), widget=forms.Select(attrs={"class": "form-select"}))
    comment = forms.CharField(required=False, widget=forms.Textarea(attrs={"class": "form-control", "rows": 3, "placeholder": "Optional comment"}))
